### ISSUE TITLE
Add topic: github-backup

### ISSUE THREAD

**Issue by katrinleinweber** [rvojcik/gitlab-project-export#1]
Thanks for publishing this! I think it would be better findable, if displayed on [GitHub.com/topics/github-backup](https://github.com/topics/github-backup), please consider [adding that topic](https://help.github.com/articles/about-topics/) to this repo. Thank you :-)

**Comment by katrinleinweber** [comment]
Bad TextExpander macro, sorry :grin:

**Comment by rvojcik** [comment]
Hi @katrinleinweber :),
thanks for reaching out. I'm not sure if it belong there becouse it's GitLAB backup instead of GitHUB :)

It export projects from www.gitlab.com or private gitlab instances. I'm not sure if people who are looking for GitHUB Backup solution ware distracted by project for backuping GitLAB :)

**Comment by katrinleinweber** [comment]
Yeah, true, but since the APIs are similar, it might still be useful to review relevant source-code. Also: https://github.com/topics/gitlab-backup ;-)

**Comment by rvojcik** [comment]
For now I don't plan to implement github, meybe somewhere in the future :)
